name: 'dbt_snow_mask'
version: '1.0.0'

require-dbt-version: [">=0.18.0", "<=0.20.0"]
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
